// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import LottieEnvelopeController from "./lottie_envelope_controller"
application.register("lottie-envelope", LottieEnvelopeController)

import TemplateModalController from "./template_modal_controller"
application.register("template-modal", TemplateModalController)

import TextStyleController from "./text_style_controller"
application.register("text-style", TextStyleController)

import PanelToggleController from "./panel_toggle_controller"
application.register("panel-toggle", PanelToggleController)